apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops
spec:
  selector:
    matchLabels:
      app: devops
  replicas: 3
  template:
    metadata:
      labels:
        app: devops
    spec:
      containers:
      - name: devops
        image: myawspk/devop-project:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
